# Generated by Django 4.2.3 on 2023-07-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("air_temp", models.IntegerField()),
                ("process_temp", models.IntegerField()),
                ("rotation_speed", models.IntegerField()),
                ("torque", models.IntegerField()),
                ("tool_wear", models.IntegerField()),
                (
                    "quality",
                    models.IntegerField(
                        choices=[(0, "Low"), (1, "Medium"), (2, "High")]
                    ),
                ),
                ("predictions", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
