# Generated by Django 4.2.3 on 2023-07-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="machinerecord",
            old_name="rotation_speed",
            new_name="rotational_speed",
        ),
        migrations.AlterField(
            model_name="machinerecord",
            name="quality",
            field=models.IntegerField(),
        ),
    ]
