# Generated by Django 4.2.3 on 2023-07-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_rotation_speed_machinerecord_rotational_speed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="machinerecord",
            old_name="name",
            new_name="machine_name",
        ),
    ]
